# phi3:
#   model_name: phi3:3.8b

# whisper:
#   model_size: base
#   device: cpu

# tts:
#   provider: elevenlabs  
#   voice_id: EXAVITQu4vr4xnSDxMaL

coqui:
  use_gpu: true
  output_dir: data/temp_audio
  speaker: null

  language_models:
    en: tts_models/en/vctk/vits
    vi: tts_models/vi/vivos/vits
    ja: tts_models/ja/kokoro/vits