# phi3:
#   model_name: phi3:3.8b

# whisper:
#   model_size: base
#   device: cpu

# tts:
#   provider: elevenlabs  
#   voice_id: EXAVITQu4vr4xnSDxMaL

vieneu:
  mode: turbo
  device: cpu
  output_dir: data/temp_audio
  model_path: "models/vieneu-tts-v2-turbo.gguf"