#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Regenerate a pinned Docker requirements lockfile from its `.in` file using `uv`.

Two variants, because the two images get PyTorch from opposite directions:

  dev (default)  `docker_requirements.in` -> `docker_requirements.txt`
                 Base image is `nvcr.io/nvidia/pytorch`, which already ships a tested
                 torch+CUDA build, so those wheels are filtered OUT of the lockfile.

  prod (--prod)  `docker_requirements_prod.in` -> `docker_requirements_prod.txt`
                 Base image is a minimal `nvidia/cuda` image with no torch, so torch and
                 its `nvidia-*` wheels are KEPT and resolved against the PyTorch index.

Usage:
  python3 kimodo/scripts/lock_requirements.py           # dev image
  python3 kimodo/scripts/lock_requirements.py --prod    # prod image

Run this from the repository root (where the `.in` files live) and commit the result.
Do not hand-run `uv pip compile`: the pins must be resolved for linux/py3.10 and, for
prod, against the PyTorch index — not for whatever machine you happen to be on.

Optional args:
  --python-version 3.10
  --python-platform x86_64-manylinux2014
  --in docker_requirements.in
  --out docker_requirements.txt
"""

import argparse
import shutil
import subprocess
from pathlib import Path
from typing import Iterable

DEFAULT_PYTHON_VERSION = "3.10"
DEFAULT_PYTHON_PLATFORM = "x86_64-manylinux2014"

# Packages to omit from the lockfile because the Docker base image already provides torch+CUDA.
OMIT_NAMES = {"torch", "triton", "networkx", "sympy", "mpmath"}
OMIT_PREFIXES = ("nvidia-",)

# The prod image installs torch itself, from the CUDA 12.4 wheel index. Resolving against
# this index at lock time is what keeps the pinned versions and the wheels Docker actually
# installs from drifting apart.
PROD_IN = "docker_requirements_prod.in"
PROD_OUT = "docker_requirements_prod.txt"
PROD_EXTRA_INDEX = "https://download.pytorch.org/whl/cu124"

PROD_NOTE = (
    "# NOTE: generated by `python kimodo/scripts/lock_requirements.py --prod`. Do not edit by hand.\n"
    "# Unlike docker_requirements.txt, this lockfile KEEPS torch and its nvidia-* wheels:\n"
    "# the prod image sits on a minimal nvidia/cuda base that supplies no PyTorch.\n"
    "# Dockerfile.base installs this with --no-deps, so this file is the sole authority on\n"
    "# what lands in the image. Local packages (./MotionCorrection, kimodo) are built\n"
    "# explicitly in the Dockerfiles and deliberately absent here.\n"
    "#\n"
)


def _run(cmd: list[str]) -> None:
    print("+", " ".join(cmd))
    subprocess.run(cmd, check=True)


def _ensure_uv() -> None:
    if shutil.which("uv") is None:
        raise SystemExit(
            "ERROR: `uv` is not installed or not on PATH.\n"
            "Install it (one of):\n"
            "  - pipx install uv\n"
            "  - python -m pip install --user uv\n"
            "Then rerun this script."
        )


def _parse_req_name(line: str) -> str:
    # uv emits `name==version` lines.
    s = line.strip()
    if "==" in s:
        return s.split("==", 1)[0].strip()
    # Fallback: treat the whole token before space as name.
    return s.split()[0].strip()


def _iter_blocks(lines: list[str]) -> Iterable[list[str]]:
    """Split a docker_requirements.txt into blocks: [top-level req line + indented comments]."""
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        # Header/comments/blank
        if line.startswith("#") or line.strip() == "":
            yield [line]
            i += 1
            continue

        # Top-level requirement line
        if not line.startswith(" "):
            block = [line]
            i += 1
            while i < n and (lines[i].startswith(" ") or lines[i].strip() == "" or lines[i].startswith("#")):
                # Stop if we hit another top-level requirement line
                if not lines[i].startswith(" ") and not lines[i].startswith("#") and lines[i].strip() != "":
                    break
                block.append(lines[i])
                i += 1
            yield block
            continue

        # Indented line without a requirement header (shouldn't happen, but keep)
        yield [line]
        i += 1


def _should_omit(req_line: str) -> bool:
    name = _parse_req_name(req_line)
    if name in OMIT_NAMES:
        return True
    for pfx in OMIT_PREFIXES:
        if name.startswith(pfx):
            return True
    return False


DEV_NOTE = (
    "# NOTE: `torch` (and its CUDA wheels) are intentionally omitted from this lockfile.\n"
    "# The Docker base image (nvcr.io/nvidia/pytorch) already provides a tested PyTorch build.\n"
    "#\n"
)


def filter_lockfile(path: Path, note: str = DEV_NOTE, omit_torch: bool = True) -> None:
    """Insert an explanatory note after uv's header, optionally dropping torch/CUDA wheels."""
    lines = path.read_text(encoding="utf-8").splitlines(True)
    out: list[str] = []

    inserted_note = False
    for block in _iter_blocks(lines):
        first = block[0]

        # After the uv header lines, insert a short note once.
        if (not inserted_note) and first.startswith("# This file was autogenerated by uv"):
            out.extend(block)
            out.append(note)
            inserted_note = True
            continue

        if first.startswith("#") or first.strip() == "":
            out.extend(block)
            continue

        if omit_torch and _should_omit(first):
            continue

        out.extend(block)

    path.write_text("".join(out), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--prod", action="store_true", help=f"lock {PROD_IN} for the production image")
    ap.add_argument("--in", dest="in_file", default=None)
    ap.add_argument("--out", dest="out_file", default=None)
    ap.add_argument("--python-version", default=DEFAULT_PYTHON_VERSION)
    ap.add_argument("--python-platform", default=DEFAULT_PYTHON_PLATFORM)
    args = ap.parse_args()

    _ensure_uv()

    in_path = Path(args.in_file or (PROD_IN if args.prod else "docker_requirements.in"))
    out_path = Path(args.out_file or (PROD_OUT if args.prod else "docker_requirements.txt"))
    if not in_path.exists():
        raise SystemExit(f"ERROR: missing {in_path}")

    cmd = [
        "uv",
        "pip",
        "compile",
        "-U",
        str(in_path),
        "-o",
        str(out_path),
        "--python-version",
        args.python_version,
        "--python-platform",
        args.python_platform,
    ]
    if args.prod:
        # Resolve against the same index Docker installs from, so the pins are pins of
        # wheels that actually exist there. `unsafe-best-match` lets uv consider PyPI and
        # the PyTorch index together instead of treating the first hit as final.
        cmd += ["--extra-index-url", PROD_EXTRA_INDEX, "--index-strategy", "unsafe-best-match"]

    _run(cmd)

    if args.prod:
        filter_lockfile(out_path, note=PROD_NOTE, omit_torch=False)
        print(f"OK: wrote {out_path} (torch + CUDA wheels kept)")
    else:
        filter_lockfile(out_path)
        print(f"OK: wrote {out_path} (filtered torch/CUDA wheels)")


if __name__ == "__main__":
    main()
