export let isAmplifyConfigured = false
export let customOutputs: Record<string, unknown> = {}

export async function initializeAmplify(): Promise<void> {
  try {
    const { Amplify } = await import('aws-amplify')
    // amplify_outputs.json is generated by `npx ampx sandbox` and is absent in
    // local/demo mode. import.meta.glob resolves to {} when the file is missing,
    // so Vite does NOT fail to build — we fall through to demo mode below.
    const loaders = import.meta.glob('../../amplify_outputs.json')
    const loader = loaders['../../amplify_outputs.json']
    if (!loader) {
      throw new Error('amplify_outputs.json not present — demo mode')
    }
    const outputs = (await loader()) as { default?: Record<string, unknown> }
    if (!outputs.default || Object.keys(outputs.default).length === 0) {
      throw new Error('Amplify outputs are empty')
    }
    // Both must be in place BEFORE configure: the callback listener so an
    // App Link arriving during start-up is not dropped, and the token storage so
    // Amplify never writes a session to the webview's localStorage first.
    const { isNative, listenForAuthCallback, useNativeTokenStorage } = await import(
      '../lib/nativeAuth'
    )
    if (isNative()) {
      await useNativeTokenStorage()
      await listenForAuthCallback()
    }

    Amplify.configure(outputs.default)
    customOutputs = (outputs.default as any).custom || {}
    isAmplifyConfigured = true
    console.log('[Auth] Amplify configured successfully')
  } catch {
    console.warn(
      '%c⚠ Amplify not configured — running in demo mode',
      'color: #f59e0b; font-weight: bold'
    )
    console.warn('[Auth] Run `npx ampx sandbox` to enable authentication')
  }
}
